on: pull_request
name: Pytests
jobs:
  build:
    name: GitHub Action for pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytypes
    - name: GitHub Action for pytest
      uses: cclauss/GitHub-Action-for-pytest@master
      with:
        args: pytest
