name: Pytests

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Python Pylin GitHub Action
      uses: fylein/python-pytest-github-action@v2
      with:
        args: pip3 install -r requirements.txt && pytest test/unit
